### ISSUE TITLE
Export weapon and mod stats

### ISSUE THREAD

**Issue by fwdekker** [fwdekker/fo76-dumps#21]
There should be a dump of weapon and weapon mod stats, including references to the CTs.

**Comment by deadadm1n** [comment]
Any news on the weapon dump?

Another note: thank you for your hard work, it made my life 100% easier.

**Comment by fwdekker** [comment]
I'm afraid I won't have time to implement the necessary scripts at least until September, possibly October. Except for bug fixes the scripts are on hiatus for now.

**Comment by fwdekker** [comment]
Weapon dumps have been added in #20, and omod dumps have been added in 7c6e9a7148456bd592fb686ed7c8e19e33789f1e.

The dumps will be included from dump version 2.4.0 onwards.

**Comment by fwdekker** [comment]
[v2.4.0 has been released](https://github.com/FWDekker/fo76-dumps/releases/tag/v2.4.0-v1.4.0.20) and include the weapon (`WEAP.csv`) and mod (`OMOD.csv`) dumps.
