### ISSUE TITLE
Dump facegen data

### ISSUE THREAD

**Issue by ice051128** [fwdekker/fo76-dumps#44]
**Describe the dump you'd like**
Can you dump the facegen data for all npcs?

**Additional context**

**Comment by fwdekker** [comment]
Thank you for opening the issue, cool idea! I have very little experience working with facegen data, so this sounds like an interesting challenge for me ^^

I think facegen data is quite different from the data that is currently exported. fo76-dumps is (at least originally) intended to help the [Fallout Wiki](https://fallout.fandom.com/) with documenting the game, and is therefore best-suited to data that changes regularly (e.g. item locations or item stats; the `tabular` type exports) and/or with data that is easily expressed on a wiki (e.g. character dialogue or contents of notes; the `wiki` type exports). But to me it seems that facegen data is neither of those two categories. So this raises two questions with me:
* Is there a need for you to regularly re-dump the latest face morphs (for example for a wiki, as part of another data dump, or to keep a mod up-to-date), or would a one-time facegen dump suffice?
* What data format do you think is most appropriate for facegen data?

**Comment by fwdekker** [comment]
Hiya. Just wanted to check whether this issue is still relevant for you, and if so, could you take a look at the questions from my previous comment?

**Comment by ice051128** [comment]
> Hiya. Just wanted to check whether this issue is still relevant for you, and if so, could you take a look at the questions from my previous comment?

It's no longer required as I have found another way to work around the issue, thanks.
