### ISSUE TITLE
Nuka-Cola Quantum X-01 EDID

### ISSUE THREAD

**Issue by efungus1913** [fwdekker/fo76-dumps#50]
Hi im an editor for the fallout wiki and needed the Editor ID for The nuka cola quantum paint for the x-01 but im kinda confused on how i open up the files (sorry if im being dense im just not the best with tech)

**Comment by fwdekker** [comment]
Hiya! No problem, I'm happy to help :-)

To get the ID for any item:
1. Go to [the release overview](https://github.com/FWDekker/fo76-dumps/releases/tag/zOverview)
2. Select the version you want the data for. If you're not sure which version you need, just use the top row. The left column is for the game's latest release, and the right column is for the latest Public Test Server release.
3. At the bottom of the selected release, under the heading "Assets", click `tabular.IDs.csv.7z` to download that file. This file contains the IDs for everything in the entire game.
4. It ends with "7z", which means it's compressed (to save bandwidth when downloading). You have to extract it first, similar to how you extract a "zip" or "rar" file, except you will need to install the [well-known](https://en.wikipedia.org/wiki/7-Zip) software [7-zip](https://www.7-zip.org/) for this. (If you're stuck here, check [this WikiHow article](https://www.wikihow.com/Open-7z-Files).)
5. After extracting the "7z" file, you will have a file called `tabular.IDs.csv`. (_Probably_ in the directory where you downloaded `tabular.IDs.csv.7z`.) Open this file in a text editor such as Notepad. (If you open it in something like Microsoft Office, it will probably say the file has too many rows.
6. In Notepad, search for the text "nuka cola quantum paint". You will jump to the row with the info about that item. 
7. The number to the left of the item is the ID of the paint.

Let me know if this helps!

**Comment by fwdekker** [comment]
Hi efungus1913, have you been able to figure out the ID, or do you need more help?

**Comment by fwdekker** [comment]
I will close this issue because it has been inactive for a while now. If you still have questions or comments, feel free to re-open the issue and/or leave a comment!
