### ISSUE TITLE
Consumables (ALCH) dump

### ISSUE THREAD

**Issue by alexananiev** [fwdekker/fo76-dumps#54]
**Describe the dump you'd like**

Would be great to have a dump of consumables (ALCH)

**Comment by fwdekker** [comment]
Hi Alex! Thanks for opening the issue. Is there any specific data you want to see included in the dump?

**Comment by alexananiev** [comment]
Hey Florine! I think about these: effects, stats (e.g., weight, value, etc.), keywords, addiction data, and description. Thanks for your work!

**Comment by fwdekker** [comment]
That should be very doable. I'll see if I can find some time to implement a script in the coming days, shouldn't be too difficult but I haven't written Pascal in a while :P

**Comment by fwdekker** [comment]
I had some time to write the script. It extracts essentially everything from the record, except a few really boring fields (such as sounds).

The export contains the following fields:
```
"File"'              // Name of the originating ESM
"Form ID"'           // Form ID
"Editor ID"'         // Editor ID
"Name"'              // Full name
"Description"'       // Description
"Weight"'            // Weight
"Value"'             // Value
"Flags"'             // Sorted list of flag names
"Addiction"'         // Editor ID of addiction (possibly null)
"Addiction chance"'  // Addiction chance
"Health"'            // Editor ID of health curve table (possibly null)
"Spoiled"'           // Editor ID of spoiled version (possibly null)
"Effects"'           // Unsorted array of effect objects. Conditions are not
                     // included
"Keywords"'          // Sorted JSON array of keywords. Each keyword is
                     // represented as `{EditorID} [KYWD:{FormID}]`
```

For example, the item _psycho_ is exported as follows:

| Column | Value |
|---|---|
| File | SeventySix.esm |
| Form ID | `0003377d` |
| Editor ID | Psycho |
| Name | Psycho |
| Description | +15% Damage and 25 Damage Resist for 3 minutes. Increases hunger and thirst. |
| Weight | 0.25 |
| Value | 30 |
| Flags | `["Food Item","Medicine","Persists on World Change","Poison"]` |
| Addiction | `AbAddictionPsycho "Psycho Addiction" [SPEL:0004BAE3]` |
| Addiction chance | 0.1 |
| Health | `NULL - Null Reference [00000000]` |
| Spoiled | `NULL - Null Reference [00000000]` |
| Effects | <pre>[<br />  {<br />    "Base Effect": "AddictionOddsPsycho \"Chance Addiction Psycho\" [MGEF:00245EFB]",<br />    "Magnitude": "25.000000",<br />    "Duration": "0",<br />    "Area": "0",<br />    "Curve Table": ""<br />  },<br />  {<br />    "Base Effect": "ExtraDamagePsycho \"Psycho: Extra Damage\" [MGEF:0024672C]",<br />    "Magnitude": "15.000000",<br />    "Duration": "SURV_Chem_Dur_Short [GLOB:0050C205]",<br />    "Area": "0",<br />    "Curve Table": ""<br />  },<br />  {<br />    "Base Effect": "FortifyDamageResistPsycho \"Psycho: Fortify Damage Resistance\" [MGEF:0024672E]",<br />    "Magnitude": "25.000000",<br />    "Duration": "SURV_Chem_Dur_Short [GLOB:0050C205]",<br />    "Area": "0",<br />    "Curve Table": ""<br />  },<br />  {<br />    "Base Effect": "SURV_AddHunger_Potion_Effect \"SURV_AddHunger_Potion_Effect\" [MGEF:00019923]",<br />    "Magnitude": "SURV_Chem_AddHungerSize_1_Normal [GLOB:000311E1]",<br />    "Duration": "0",<br />    "Area": "0",<br />    "Curve Table": ""<br />  },<br />  {<br />    "Base Effect": "SURV_AddThirst_Potion_Effect_Chem \"Chems: Thirst\" [MGEF:000197D3]",<br />    "Magnitude": "SURV_Chem_AddThirstSize_2_Normal [GLOB:00019941]",<br />    "Duration": "0",<br />    "Area": "0",<br />    "Curve Table": ""<br />  }<br />]</pre> |
| Keywords | <pre>[<br />  "AddictionKeywordPsycho [KYWD:00245F07]",<br />  "ChemTutorialKeyword [KYWD:0037E0BC]",<br />  "ChemTypePsycho [KYWD:005477E6]",<br />  "ObjectTypeChem [KYWD:000F4AE7]"<br />]</pre> |

What do you think? Is anything missing, or could something be improved?

**Comment by alexananiev** [comment]
It looks great! 
I can't check the dump file itself yet. It doesn't seem to be included with the latest [release attachment](https://github.com/FWDekker/fo76-dumps/releases/tag/v3.1.0-v1.7.4.6).

**Comment by fwdekker** [comment]
Happy to hear that!

Release v3.1.0-v1.7.4.6 was actually a missing release from the previous script version. I'll include the ALCH dumps as of v3.2.0, which I will probably release tomorrow :-)

**Comment by fwdekker** [comment]
Since FO76 was updated today, I decided to re-run the (old) v3.1.0 scripts for the new release first. I hope to have time to run the v3.2.0 scripts tomorrow. (I'd leave the PC on in the night, but it makes too much noise.)

**Comment by fwdekker** [comment]
The v3.2.0 dumps have now been released, sorry for the delay. [One for PTS](https://github.com/FWDekker/fo76-dumps/releases/tag/v3.2.0-v1.7.4.15) and [one for main release](https://github.com/FWDekker/fo76-dumps/releases/tag/v3.2.0-v1.7.4.21).

Let me know if you have any issues or want to see any other changes.

**Comment by alexananiev** [comment]
Great! Awesome job! I will create a new issue in case something needs to be added. Thanks!
